### ISSUE TITLE
[Anon] Legiones Astartes: The squad size is capped at 3.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#107]
**Problem:**
The squad size is capped at 3.

**Expected:**
I should be able to bring 4 in this detachment

**List:** https://www.newrecruit.eu/app/list/ph6Rz
**Unit:** Legion Outrider Squadron, id: 1f92-8eda-4011-5c3b

**Comment by TrentBartlem** [comment]
It's 3 sets of 2 Outriders. Note the size of the detachment is 6, they have 6 of each weapon and increase the formation's break point by 3.
