### ISSUE TITLE
[Anon] Legiones Astartes: I cannot mix the weapons among the tanks . Legion predator tanks

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#108]
**Problem:**
I cannot mix the weapons among the tanks . Legion predator tanks

**Expected:**
Possibilty to load each tank with a different weapon

**List:** https://www.newrecruit.eu/app/list/6e0BL
**Unit:** Legion Predator Squadron, id: be26-7f4-3c1c-f7ad

**Comment by Dunamis55** [comment]
For reference, I've set a default amount to have the initial 3 tanks be separately configurable models in the unit, but this can be done manually by the user with this button:
![image](https://github.com/user-attachments/assets/86f4b334-abfb-49b1-9ade-5b48d9b41e30)
