### ISSUE TITLE
Legion Imperialis: Issues with aerial assault detachment

### ISSUE THREAD

**Issue by Scout1032** [BSData/Horus-Heresy-Legions-Imperialis#109]
Unless the website I'm using is out of date. 
1. There should be 4 spaces for core units instead of 3

2. The rule states that units CAN be upgraded to with aerial transports, and that any who aren't upgraded can simply be embarked on an aircraft in the army.  But the builder says it's required. I know it's minor, but for someone like me, it can get annoying seeing all the errors despite them technically being wrong. 

Thank you and sorry if this is a minor issue.
![IMG_1710](https://github.com/user-attachments/assets/da827cbb-1db2-4210-984f-d05ab35e1d4d)
![IMG_1709](https://github.com/user-attachments/assets/36dd964c-e33e-4d4e-9485-8ca1136d77c9)
![IMG_1713](https://github.com/user-attachments/assets/1c81aefe-acdb-4eae-9801-0e7b44fa93f2)
![IMG_1711](https://github.com/user-attachments/assets/b0260069-7cbc-4dd9-b65d-15a62d766e3f)
![IMG_1712](https://github.com/user-attachments/assets/15078876-d0ff-4b24-b7d1-da7da5412d86)

**Comment by Dunamis55** [comment]
For 1) The Core units are 1x Core and 1x Vanguard, not 2x Core:
![image](https://github.com/user-attachments/assets/8c2b5920-6e6b-46fe-8873-d3862af85c22)
