### ISSUE TITLE
[Anon] Legiones Astartes: There is No way to include Tank Commander or it really well hidden

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#111]
**Problem:**
There is No way to include Tank Commander or it really well hidden

**Expected:**
Missing everything about tank commanders (every variant of sicarian, predator and kratos commander)

 **Additional Info:**
https://epicheresy.ru/the_legiones_astartes/detachments/

**Comment by TrentBartlem** [comment]
It's on the to-list, and tracked as #83

**Comment by TrentBartlem** [comment]
Duplicate
