### ISSUE TITLE
[Anon] Legiones Astartes: There is no option for just specialized marines even though you can do that in game

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#121]
**Problem:**
There is no option for just specialized marines even though you can do that in game

**Expected:**
Different types marines added as as option

 **Additional Info:**
Legions imperialis rulebook

**List:** https://www.newrecruit.eu/app/list/huoQ5
**Unit:** Legion Tactical Detachment[6], id: e552-7189-ccb5-1922

**Comment by TrentBartlem** [comment]
You can, they're just support formations, not core formations.

Also, all bets are off if you're using an unbound formation. For open play, anything goes
