### ISSUE TITLE
[Anon] Strategic Assets: Warhound titans are worth too many points

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#123]
**Problem:**
Warhound titans are worth too many points

**Expected:**
Two warhound titans should be 660pts not 970

 **Additional Info:**
Legions Imperialis Rulebook

**List:** https://www.newrecruit.eu/app/list/72TK2
**Unit:** Warhound Hunting Pack[1], id: 81ba-90a7-a52e-64cc

**Comment by TrentBartlem** [comment]
1 hunting pack is 660

2 hunting packs are 970 each. Might be a [shared] flag
