### ISSUE TITLE
Legion Demi-Company Formation

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/Horus-Heresy-Legions-Imperialis#2]
Data from [Legions Imperialis Core Concepts – This Is How the New Game Plays](https://www.warhammer-community.com/2023/07/31/legions-imperialis-core-concepts-this-is-how-the-new-game-plays/):

Legiones Astartes Formation 

- [x] Legion Demi-Company

Details [in this image](https://www.warhammer-community.com/wp-content/uploads/2023/07/ANb6of4DaF7wp0Al.jpg)

Also these formations exist but with no details yet

- [x] Legion Armoured Company
- [x] Legion Aerial Assault

**Comment by Dunamis55** [comment]
All Formations now added to Legions Astartes catalogue.
