### ISSUE TITLE
warlord loadout

### ISSUE THREAD

**Issue by Depthswalker** [BSData/Horus-Heresy-Legions-Imperialis#22]
**Describe the bug**
warlord has Arioch power claw as a non-optional weapon that even if you manually remove produces a warning that it must have it.

**To Reproduce**
select warlord

**Expected behavior**
arioch would be an optional weapon like any other

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists : Battlescribe
 - App version : 2.03.21.166
 - Data release version : v1.0.2

**Additional context**

**Comment by Dunamis55** [comment]
Fixed in next data release.
