### ISSUE TITLE
[Anon] Bug report: Legiones Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Horus-Heresy-Legions-Imperialis#23]
**File:** Legiones Astartes.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** Yes

**Description:** I am attempting to make a list for the Astartes from the starter box bit i am not finding the Contemptor Dreadnoughts anywhere. Are they in the file or do they still need to be added?

**Comment by TrentBartlem** [comment]
`Legion Dreadnought Talon` is a Support detachment that consists of four Contemptor Dreadnaughts. It has been in the list since release. Have you updated to a current version?

**Comment by Dunamis55** [comment]
Not a Bug / Working as Intended - Contemptor Dreadnoughts are a part of the Legion Dreadnought Talon.
