### ISSUE TITLE
Solar Auxilia - Malcador Tanks

### ISSUE THREAD

**Issue by preastham** [BSData/Horus-Heresy-Legions-Imperialis#27]
The points cost of the **Malcador Tank** is broken if it is in an **Armoured Company** which **also includes a Leman Russ Detachment**

On their own the Malcador tank costs 165 points, however once included with a leman russ detachment the cost jumps to 295 points, then up to 365 points when the 1st compulsory upgrade is included and 405 points when both upgrades are setup !!

**Comment by TrentBartlem** [comment]
I believe this is covered by issue #26

**Comment by TrentBartlem** [comment]
Fixed in [v1.0.5](https://github.com/BSData/Horus-Heresy-Legions-Imperialis/releases/tag/v1.0.5)
