### ISSUE TITLE
Data from A Closer Look at the Legiones Astartes

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/Horus-Heresy-Legions-Imperialis#3]
https://www.warhammer-community.com/2023/08/02/legions-imperialis-a-closer-look-at-the-legiones-astartes/

- [x] Each Legiones Astartes detachment may have a Legion attribute
  - [x] White Scars Legion Special Rule
  - [x] World Eaters legion Special Rule
  - [x] Salamanders Legion Special Rule
- [x] Legion Terminator Detachment
- [x] Legion Kratos Squadron
- [x] Legion Thunderhawk Gunship

**Comment by zopha** [comment]
The space wolves special rule was published on Facebook by warhammer community just after this article. I'll see if I can find it again.

**Comment by zopha** [comment]
Second comment here

https://m.facebook.com/100065069820744/posts/663141365864852/

I can add an image if needed.

**Comment by Dunamis55** [comment]
All now fully implemented in the data.
