### ISSUE TITLE
[Anon] Bug report: Legiones Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Horus-Heresy-Legions-Imperialis#30]
**File:** Legiones Astartes.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Horus Heresy, Legion Rapier Battery,i do not think the bulky rule is being applied to the stands. minimum size would be 2 stands taking up 4 transport slots.

**Comment by Dunamis55** [comment]
Working as intended / Not a Bug - If you take any Thunderhawks as Dedicated Transports, they treat Bulky units as a Transport cost of 1 since they are Large Assault Transports. Storm Eagles still treat them as Bulky with a Transport cost as 2.
