### ISSUE TITLE
Knight warden costs 4 extra points for no reason

### ISSUE THREAD

**Issue by Komrad33** [BSData/Horus-Heresy-Legions-Imperialis#31]
**Describe the bug**
Knight warden is 4 extra points.

**To Reproduce**
add knight warden, they cost 4 extra points for no reason.

**Expected behavior**
Knight warden not costing 4 extra points.

**Screenshots**
![image](https://github.com/BSData/Horus-Heresy-Legions-Imperialis/assets/123283918/546c6073-3436-4d79-82e3-5e9cfb797574)

**Device and data (please complete the following information):**
 - OS: iOS Mac OS Win 11
 - Battlescribe 
 - latest
 - 1.0.5

**Additional context**

**Comment by TrentBartlem** [comment]
Confirmed, Melta and gatling cannon are +2pts each for some reason
