### ISSUE TITLE
Heavy Stubber range/To hit/AP on Questoris knights is wrong

### ISSUE THREAD

**Issue by Komrad33** [BSData/Horus-Heresy-Legions-Imperialis#32]
**Describe the bug**
Range on heavy stubbers in LI book is listed at 14" in data files at 6"
To hit is wrong too listed at 5+ in the book, 4+ in data files
Ap is wrong as well, Book lists 0, -3 in data files

**To Reproduce**
Range should be 14"
to hit should be 5+
AP should be 0

**Screenshots**
![image](https://github.com/BSData/Horus-Heresy-Legions-Imperialis/assets/123283918/eb8a7f91-bc58-4f47-89db-fe4805eda5d1)

**Device and data (please complete the following information):**
 - OS: iOS win 11 Mac os
 - Battlescribe
 - latest
 - 1.0.5

**Comment by TrentBartlem** [comment]
Confirmed
