### ISSUE TITLE
Points for tanks too high

### ISSUE THREAD

**Issue by TimRascher** [BSData/Horus-Heresy-Legions-Imperialis#35]
When purchasing tanks, they have a variable cost per tank depending on the upgrade you choose. For example, a base Legion Kratos Squadron is 150 points with 2 tanks. Then you can buy the following upgrades as many times as you want as long as the Squadron doesn’t go past 6 tanks.
1 for 60 points
2 for 110 points
4 for 200 points

Right now you can only buy tanks 1 at a time and it seems to be adding the costs. So 4 tank Kratos Squadron is costing 320 (150+60+110) instead of just 260 (150+110). Or for a full unit of 6 tanks it’s coming up at 470 (150+60+60+200) instead of 350 (150+200).

Seems like all the tanks do this, way over costing for the amount of models.

**Comment by TrentBartlem** [comment]
I think the issue is that some of the intermediate steps that add one tank have
`<condition type="atLeast" value="3" ...` (or 5) when they should have `<condition type="equalTo"...`
