### ISSUE TITLE
Data from A Closer Look at the Solar Auxilia

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/Horus-Heresy-Legions-Imperialis#4]
https://www.warhammer-community.com/2023/08/07/legions-imperialis-a-closer-look-at-the-solar-auxilia/

- [x] Solar Auxilia Army Rule: Chain of Command
- [x] Solar Auxilia Army Rule: Close Formation Fighting
- [x] Formation: Solar Auxilia Sub-Cohort ([image](https://www.warhammer-community.com/wp-content/uploads/2023/08/Neb3aFhcjX4v8jPx.jpg))
- [x] Formation: Solar Auxilia Armoured Company ([image](https://www.warhammer-community.com/wp-content/uploads/2023/08/pybobo4UsRRTOUNK.jpg))
- [x] Leman Russ Strike Squadron
- [x] Auxilia-Super Heavy Tanks Squadron

**Comment by Dunamis55** [comment]
All now implemented
