### ISSUE TITLE
[Anon] Bug report: Horus-Heresy-Legions-Imperialis.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Horus-Heresy-Legions-Imperialis#49]
**File:** Horus-Heresy-Legions-Imperialis.gstz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Using the repository address from this site for Imperialis isn't working in the app as the game system does not appear.

**Comment by Dunamis55** [comment]
BattleScribe issues / can't fix - Recommend using [NewRecruit](https://www.newrecruit.eu/) instead, as BattleScribe is abandonware.
