### ISSUE TITLE
Data from Give Battle With a Support Lance of Knights

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/Horus-Heresy-Legions-Imperialis#5]
https://www.warhammer-community.com/2023/08/14/legions-imperialis-give-battle-with-a-support-lance-of-knights/

- [x]  Formation: Knight Household Lance
- [x] must choose 1 Knight Banner (detachment): 
  - [x] Questoris Knight Banner (1..3 knights)
  - [x] Cerastus Knight Banner(1..3 knights)
  - [x] Acastus Knight Banner(1..2 knights)
- [x] 0..1 optional formation
  - [x] Questoris Knight Armiger Talon
  - [x] Mechanicum Knight Moirax Talon
- [x] Ion Shield (x) rule
- [x] Engine Killer (X) attribute

**Comment by Dunamis55** [comment]
All now implemented in the data.
