### ISSUE TITLE
Legiones Astartes - Sky-Hunter Phalanx minimum detachment limits aren't working correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Horus-Heresy-Legions-Imperialis#53]
**File:** Horus-Heresy-Legions-Imperialis.gstz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Legions Astartes, Phalanx formation, I found these errors:
Javelin are priced at 99 points for 6 bases. The correct price Is 33 per 2 basis, plus 33 adding 2 (to a maximum of 6).
The formation actually include between optional detachements only Air support and Vanguard. Missing the options of 2 light armour.
Finally, the error allert ask for 4 units of speeders, 4 units of jetbike and 4 units of javelin, while the compulsory are a Total of 4 between the above choice.

**Comment by Dunamis55** [comment]
Not a Bug / Working as Intended - Javelins cost 33/66/99 for 2/4/6 bases, which is what the data is doing.

The Formation minimum amounts are indeed bugged though.
