### ISSUE TITLE
[missing trait] Direwolf missing Infiltrate Trait and having void shields twice

### ISSUE THREAD

**Issue by JackACEJolleboi** [BSData/Horus-Heresy-Legions-Imperialis#55]
**Describe the bug**
The Direwolf Heavy Scout Titan is missing the Infiltrate trait from its data sheet. in addition, while it correctlt lists the void shields (2) trait, it incorrectly lists void shields (x), which is uncessesary.

**To Reproduce**
1. create a legions imperialis list with strategic asset legion support
2. add a direwolf heavy scout titan
3. view the direwolf's data sheet and check the listed traits

**Expected behavior**
According to page 213 of the legions imperialis core rulebook, the Direwolf heavy scout titan is supposed to have the Infiltrate trait. I would expect this trait to be seen when checking the data shete in battlescribe. 
In addition, i would expect to only see the Void Shields rule listed once, and not twice.

**Screenshots**
![direwolfError](https://github.com/BSData/Horus-Heresy-Legions-Imperialis/assets/113132308/4ab06e87-9d36-407f-964e-15847b0e647f)

**Device and data (please complete the following information):**
 - OS: Win11
 - App being used to create lists: Battlescribe
 - App version: 2.03.21
 - Data release version: v1.1.5

**Additional context**
Having one of the most significant rules for a unit not shown in its data sheet is something that can make people quickly dismiss the unit, or use it inaccurately. The existance of the same rule twice is less of an issue, but it does clutter the data sheet with extra uneccesary text.

**Comment by TrentBartlem** [comment]
ha, someone renamed Infiltrate to Void Shields (2) by accident
