### ISSUE TITLE
No longer available on Battle Scribe, missing link in readme

### ISSUE THREAD

**Issue by tympaniplayer** [BSData/Horus-Heresy-Legions-Imperialis#63]
**Describe the bug**
As it says. Apologies if I missed an announcement, but this is no longer available to pick as a source in BattleScribe 

**To Reproduce**
1. Open BattleScribe (mobile or desktop)
2. Click on sources
3. Click on manage sources / add sources
4. Horus Heresy Legion Imperialis missing

**Expected behavior**
It should be there 

**Screenshots**

![image](https://github.com/BSData/Horus-Heresy-Legions-Imperialis/assets/1745731/e909065d-f004-4be5-8b6e-1f531da0fe6c)

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe
 - N/A as it's not listed. 

**Additional context**

**Comment by Dunamis55** [comment]
Appspot, which is what BattleScribe uses to track data repositories, breaks often. As BattleScribe is also abandonware, it's better to switch over to [NewRecruit](https://www.newrecruit.eu/), which is actively maintained and doesn't have this problem.
