### ISSUE TITLE
Legion Kratos hull weapons aren't doubled

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/Horus-Heresy-Legions-Imperialis#66]
**Describe the bug**
Datasheet says '**two** hull mounted heavy bolters or two kratos lascannon or two kratos autocannon'

but this is not reflected in the data, which only has one of those weapons per vehicle.

So it either needs 2x that weapon, or the weapon profile to be doubled.

**Comment by Dunamis55** [comment]
Not a data bug - is working correctly in the data, but needs a UI/UX improvement to be implemented into NewRecruit.
