### ISSUE TITLE
[Anon] Strategic Assets: Unable to increase the detachment size of basilisk without an error

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#79]
**Problem:**
Unable to increase the detachment size of basilisk without an error

**Expected:**
No error. Should be able to increase detachment size 

**List:** https://www.newrecruit.eu/app/list/BNi7u
**Unit:** Auxilia Basilisk Battery, id: 16e5-7599-68d3-b1e

**Comment by TrentBartlem** [comment]
How are you adding basilisks without using the 'add 4 more basilisks' button?

![image](https://github.com/user-attachments/assets/f4d873bb-514d-4c2e-9a2b-95a2c5f25cf6)

**Comment by Dunamis55** [comment]
Please untick the option to show constant unit options from the NewRecruit's settings and you shouldn't have this problem when creating units:
![image](https://github.com/user-attachments/assets/c32a2b9b-86c6-4886-bb07-fb0f99814baa)
