### ISSUE TITLE
[Anon] Solar Auxilia: Legate commander cannot be taken, maximum of zero per list

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#82]
**Problem:**
Legate commander cannot be taken, maximum of zero per list

**Expected:**
It should be able to be taken 

**List:** https://www.newrecruit.eu/app/list/3KgZV

**Comment by TrentBartlem** [comment]
Fixed by cc6ae3570165548ad3f649b4b07384a09b722bdc
