### ISSUE TITLE
[Anon] Solar Auxilia: Mechanicum Knight Moirax Talons are missing the "Light AT" Keyword on their Lightning Locks

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#87]
**Problem:**
Mechanicum Knight Moirax Talons are missing the "Light AT" Keyword on their Lightning Locks

**Expected:**
They have the Keyword

**Comment by TrentBartlem** [comment]
They do not have Light AT in the detachment upgrade profile (p211), which supersedes the weapon profile summary on p236. 

Until an errata states which is correct, we will go with the one on the detachment profile.
