### ISSUE TITLE
[Anon] Legiones Astartes: Assault marines need dreadnought drop pods 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#96]
**Problem:**
Assault marines need dreadnought drop pods 

**Expected:**
Dreadnought drop pods

 **Additional Info:**
Jump packs count as bulky for transport.  

**List:** https://www.newrecruit.eu/app/list/mrhxt
**Unit:** Legion Tactical Detachment[1], id: e552-7189-ccb5-1922

**Comment by TrentBartlem** [comment]
Rules as written, you cannot take assault marines in that formation, because they do not fit in Legion Drop Pods.

> All Legiones Astartes Detachments within the Formation that contain only Infantry models (excluding models with the Deep Strike special rule) must be upgraded with Legion Drop Pods as Dedicated Transports, and all Legiones Astartes Detachments within the Formation that contain only Walker models (excluding models with the Deep Strike special rule) must be upgraded with Dreadnought Drop Pods as Dedicated Transports.
