### ISSUE TITLE
[Anon] Legiones Astartes: This Detachment dictates that any unit without a Flyer keyword must be embarked on a Flyer Transport, this can be done via HQ Squad + Storm Eagle (Dedicated Transport)+ 2 x 2 Base Tactical Legionaries. Totaling 5 Transport value of the Storm Eagle Transport Keyword (X), X=5.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/Horus-Heresy-Legions-Imperialis#98]
**Problem:**
This Detachment dictates that any unit without a Flyer keyword must be embarked on a Flyer Transport, this can be done via HQ Squad + Storm Eagle (Dedicated Transport)+ 2 x 2 Base Tactical Legionaries. Totaling 5 Transport value of the Storm Eagle Transport Keyword (X), X=5.

**Expected:**
We would need an option to toggle off the Error and select Troops + HQ in X Flyer Transport ( either Storm Eagle or Thunderhawk up to Transport(X) value.

**List:** https://www.newrecruit.eu/app/list/2ZYAf
**Unit:** Legion Tactical Detachment[1], id: e552-7189-ccb5-1922

**Comment by Dunamis55** [comment]
Not a Bug / Working as Intended - You can't put multiple different detachments in a Dedicated Transport:
![image](https://github.com/user-attachments/assets/7f687539-f645-4343-91f6-220c9cfc9e80)
